### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by apierr** [devw/stag#29]
### 3 Feb
1. [ ] testing the `login-popup app `on different browsers and devices
2. [x] Customize Error Message Locations
![Screenshot 2021-02-03 at 09 20 16](https://user-images.githubusercontent.com/1194257/106718394-4b582380-6601-11eb-8233-05f672186adb.png)
3. [ ] Improving UX on mobile (setting date/time is very laborious and time-consuming)

### 1 Feb
1. [x] Checking the metafield storage
```
const SCOPES = [
     "read_script_tags",
     "write_script_tags",
     "read_customers",
+    "write_customers",
 ];
```

2. [ ] Improving TTFB (Time To First Byte) from Amazon  S3 (900 ms). A possible solution would be to use a small EC2 instance.
3. [x] Adding button loading animation
### 29 Jan
2. [x] Fix the landing page logic
    - Preconditions: 
       - antonio@gmail.com is a registered customer.
       - antonio@gmail.cop is not a registered customer.
       - the landing form have been submitted with antonio@gmail.com
     - Postcondition
       - when the landing form is submitted with antonio@gmail.cop, the customer will be redirected to the register page
3. [x] Activate the password recovery link and implement the server request!
5. [x] Improve customer experience on mobile.
6. [x] reduce customer waiting times by trying as much as possible to use client-side checks 
4. [x] Disable possible automatic proxy caching.
1. [ ] What should I do when the Shopify response status code indicates the user has sent too many requests in a given amount of time? (status code = 429). We have two options:
   -  redirect the customer on `Shopify Error Page` 
   -  keep  `popup-login app` open (without reloading the page) advising the user to wait a few minutes before to login/recover/register again.
2. [ ] What should we do when the customer recover the password? We have different options:
   - let Shopify redirect the customer on `account/login page`.
   - If the captcha is not required, we prevent Shopify to load  the `account/login page`. We keep the `popup-login app` open with instructions to check email and rewrite the password.
   - If the captcha is required, we let the customer solve the captcha and then when Shopify reload the `account/login page`, we open the `popup-login app` on the login page with the email autofill.
  
### 27 Jan 2021
1. [x] fix the edit of choice list into customize ("supprimez la section" event should remove the list)
2. [x] improve the get-customer-status call. (`get-customer-status` is called instantly when the email format is correct and then before to make another call I will make the following checks 
a) `stackEmails.every((e) => !RegExp(`^${e}`, "i").test(email))) // anto@gmal.co , anto@gmal.com -> false` 
b) debounce the next calls
c) should I store the active useer into localStorage to avoid unnecessary calls?
3. [ ] Should I disable the form submission on the customize app?
4. [ ] Some sections (register-page, login-page) should be non-removable
5. [x] adding the` date block `(tag and metafield)
6. [ ] It takes too long to download the scripttag (500ms, although it is 26K). Is there a 'cold start' in AWS S3?
7. [ ] The choice in the password policy does not remain selected. (try to save and reload the page!)

### 25 Jan 2021
1. - [x] Recovering password on the login page.
2. - [x] Optimizing the scriptTag performance: 1) reducing the scriptTag size from 36K to 26K . 2) fetching the scriptTag from S3 (before, it was fetched from github)
3. - [x] How should the Kastor link change to point to a different shop?
___

![Screenshot 2021-01-18 at 14 15 56](https://user-images.githubusercontent.com/1194257/104920317-e4e3cc00-5997-11eb-8dd6-03a5b0d56534.png)

1. - [ ] I want to save a text field without URL, but I can't (*). Should I add a checkbox field to set/unset the background image?
2. - [ ] Some text fields must be mandatory. For instance, the "tag prefix" to store data as TAG or the pair (namespace, key) to store data as Metafield. Now I can save these text fields even if they are not specified.
3. - [x] What method should I use to activate the user? (remove the form, it will be just a message)
4. - [x] Adding opacity on the background image.
5. - [x] Move `set-metafield-in-Shopify` in `Serverlesss`
6. - [x] Move `get-customer-status` in `Serverlesss`
7. - [x] Validate the`proxy request`(**) to get the shopName.  (only for scriptTag request)
8. - [x] Removing the debouncing method.
9. - [x] Date Check
10. - [x] Implement `set-metafield-in-DDB` in `Serverlesss`
11. - [x] I need to compare validate the `customer_metafileds` with metafields set in DDB before storing them into Shopify.
12. - [x] Making POST request (checking the email) processed in the background as soon as the email is valid!
13. - [ ] Social Login
14. - [x] Should I add a button for`recovery password` on` login page`? Should I add a new setting on kastor to customize the password recovery page?

15. - [x] The script tag is the last resource to be loaded. When the connection is not good, the customer could click on the login button before the app is loaded. 
16. - [ ] Automatic testing with GitHub Actions.  [x] Jest Setup,  [x ] Mocking HTTP Requests, [ ] User Actions 

(*) 
![Screenshot 2021-01-22 at 12 35 37](https://user-images.githubusercontent.com/1194257/105486517-e91d2b80-5cae-11eb-9352-7d07d76c3e04.png)

----
<!--

1. - [ ] How to delete a block from Kastor interface? (discussing with Thomas)

1. - [ ] Should "sorting blocks" action trigger the order of input fields in the registration form?
1. - [ ] The difference between date and birthdate
2. - [ ] To each update the DOM grows up! (see dot.js) 
3. - [ ]  Ordering flexible items (blocks) https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordonner_%C3%A9l%C3%A9ments_flexibles

1. - [ ] Admin  Panel in React (2 hours)
```
- button to activate/deactivate
- link for customizing the theme
```

5. - [ ] Test the submit form for 1) registering a new user, 2) loggining a new user, 3) activating an existing user (30 min)

5. - [ ] Testing the metadata values storing such as phone, date of birth, etc. (1 hour)

5. - [ ] Redirecting New Customers After Registration/login. It does not work! (30 min)
https://community.shopify.com/c/Shopify-Design/Redirecting-New-Customers-After-Registration/td-p/335817

```
    <input
        type="hidden"
        name="return_to"
        value="{{=it.redirectAfterRegister}}"
    />
```
 
- [ ] Adding image icons. (30 minutes)

- [x] Hardcoded value into `config.yml`. **No Multiple Language Support**. (3 hours)

- [ ] Setting the background image with opacity. Now it is a hardcoded value. (30 min.) <!-- opacity selector (10 min.) https://webcode.tools/css-generator/outline 

- [x] Adding a block triggers an error (2 hours)

- [ ] Auto-open popup on Kastor. I cannot read URL parameter from the iframe (30 minutes)

___

- [ ] Missing variables in customize file (config.yml)

<img src="https://user-images.githubusercontent.com/1194257/102626832-a0ba9d00-4147-11eb-9e02-a982f5b1a0ef.png">

- [x] Cache issue in getting the configuration file from S3 (10 minutes)
```
    const result = await globalThis.fetch(endpoint, {
        headers: { pragma: "no-cache" },
    });
    return await result.json();
```-->
